site_name: Gluu Support Portal Docs
site_description: Documenation for the Gluu Support portal 
site_favicon: '/img/gluu_favicon.ico'
copyright: Copyright &copy; 2016, Gluu, Inc.
docs_dir: sources
repo_url: https://github.com/GluuFederation/support-portal-docs
theme: readthedocs
theme_dir: ./theme/mkdocs/

markdown_extensions:
- admonition

pages:

- Home: 'index.md'
- User Guide: 
    - 'Using Gluu Support Portal': 'user-guide/index.md'
    - 'How to Create a Good Ticket': 'user-guide/how-to-ask.md'
- Administaration Guide: 'admin-guide/index.md'
- Developer Guide: 'developer-guide/index.md'
